discourse_github_sponsors:
  github_sponsors_enabled:
    default: false
    client: true
    description: "Enable GitHub Sponsors sync"

  github_sponsors_group_name:
    default: "sponsors"
    type: string
    description: "The Discourse group to sync sponsors to"

  github_sponsors_account:
    default: ""
    type: string
    description: "GitHub username/org to check sponsors for"
    validator: "GithubAccountValidator"
    client: true

  github_sponsors_token:
    default: ""
    type: secret
    description: "GitHub API token for fetching sponsor data (requires scopes: read:org, read:user, user:email)"
    validator: "GithubTokenValidator"

  github_sponsors_flair_icon:
    default: "fab-github"
    type: string
    description: "Font Awesome icon for sponsor flair (e.g. 'fab-github', 'seedling')"
    client: true

  github_sponsors_flair_color:
    default: "ffffff"
    type: string
    description: "Text color for sponsor flair (hex without #)"
    client: true

  github_sponsors_flair_bg_color:
    default: ""
    type: string
    description: "Background color for sponsor flair (hex without #, leave blank for no background)"
    client: true

  github_sponsors_sync_history_retention_days:
    default: 30
    type: integer
    min: 7
    max: 365
    description: "Number of days to retain sync history records (older records are automatically deleted)"

  github_sponsors_verbose_log:
    default: false
    description: "Enable verbose logging for GitHub Sponsors sync operations"

  discord_server_guild_id:
    default: ""
    type: string
    description: "Discord server (guild) ID for sponsor access"
    validator: "DiscordGuildIdValidator"

  discord_invite_channel_id:
    default: ""
    type: string
    description: "Discord channel ID to generate invite links for"
    validator: "DiscordChannelIdValidator"

  discord_bot_token:
    default: ""
    type: secret
    description: "Discord bot token (requires CREATE_INSTANT_INVITE and VIEW_CHANNEL permissions)"
    validator: "DiscordBotTokenValidator"

  discord_webhook_url:
    default: ""
    type: string
    description: "Optional Discord webhook URL for notifications when invites are generated"
    validator: "DiscordWebhookValidator"

  discord_invite_max_age:
    default: 3600
    type: integer
    min: 1800
    max: 86400
    description: "How long Discord invite links are valid (in seconds, default 1 hour)"
